import re
import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional

# ---------------------------------------------------------------------------
# Pattern definitions
# ---------------------------------------------------------------------------

PATTERNS = [
    {
        "id": "SEC001",
        "name": "AWS Access Key",
        "severity": "critical",
        "category": "hardcoded_secret",
        "pattern": r"AKIA[0-9A-Z]{16}",
        "description": "AWS Access Key ID bị hardcode trong source.",
        "recommendation": "Dùng os.environ hoặc AWS Secrets Manager. Xoay key ngay lập tức.",
    },
    {
        "id": "SEC002",
        "name": "AWS Secret Access Key",
        "severity": "critical",
        "category": "hardcoded_secret",
        "pattern": r"(?i)(aws.{0,20}secret.{0,20}['\"])[A-Za-z0-9/+=]{40}",
        "description": "AWS Secret Access Key bị hardcode.",
        "recommendation": "Dùng IAM roles hoặc AWS Secrets Manager.",
    },
    {
        "id": "SEC003",
        "name": "Generic API key assignment",
        "severity": "critical",
        "category": "hardcoded_secret",
        "pattern": r"(?i)(api_key|apikey|api_secret|secret_key|access_token|auth_token)\s*=\s*['\"][A-Za-z0-9_\-]{16,}['\"]",
        "description": "API key hoặc secret token được gán trực tiếp dưới dạng string.",
        "recommendation": "Đọc từ environment variable: os.environ['API_KEY']",
    },
    {
        "id": "SEC067",
        "name": "IPv4 Hardcoded (Public)",
        "severity": "low",
        "category": "misconfiguration",
        "pattern": r"\b(?:[1-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(?:\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(?:\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(?:\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\b",
        "description": "IP có thể bị hardcode trong source.",
        "recommendation": "Chuyển sang biến môi trường nếu đó là IP dịch vụ.",
    },
    # ── CWE-89: SQL INJECTION ──────────────────────────────────────────────
    {
        "id": "SEC071",
        "name": "SQL Injection (PHP)",
        "severity": "critical",
        "category": "injection",
        "pattern": r"(?i)(mysql_query|mysqli_query|PDO::query)\s*\(\s*.*\$_(GET|POST|REQUEST|COOKIE)",
        "description": "SQL Injection qua nối chuỗi trực tiếp từ user input (PHP).",
        "recommendation": "Sử dụng Prepared Statements (PDO prepare/execute).",
    },
    {
        "id": "SEC072",
        "name": "SQL Injection (Node.js/JS)",
        "severity": "critical",
        "category": "injection",
        "pattern": r"(?i)(\.query|\.execute)\s*\(\s*[`\"'].*(SELECT|UPDATE|INSERT|DELETE).*\$\{[^}]+\}.*[`\"']",
        "description": "SQL Injection qua Template Literals hoặc nối chuỗi (Node.js).",
        "recommendation": "Sử dụng Parameterized Queries (dấu ? hoặc $1).",
    },
    {
        "id": "SEC073",
        "name": "SQL Injection (Java)",
        "severity": "critical",
        "category": "injection",
        "pattern": r"(?i)(createStatement\(\)\.execute(?:Query|Update)?\s*\(\s*.*(?:\+|concat).*request\.getParameter)",
        "description": "SQL Injection qua nối chuỗi trong JDBC (Java).",
        "recommendation": "Sử dụng PreparedStatement thay vì Statement.",
    },

    # ── CWE-79: CROSS-SITE SCRIPTING (XSS) ─────────────────────────────────
    {
        "id": "SEC074",
        "name": "Reflected XSS (PHP)",
        "severity": "high",
        "category": "xss",
        "pattern": r"(?i)(echo|print|printf|die|exit)\s*\(?\s*.*\$_(GET|POST|REQUEST)",
        "description": "In trực tiếp dữ liệu người dùng ra trình duyệt gây XSS.",
        "recommendation": "Sử dụng htmlspecialchars() trước khi hiển thị.",
    },
    {
        "id": "SEC075",
        "name": "DOM XSS (JavaScript)",
        "severity": "high",
        "category": "xss",
        "pattern": r"(?i)(\.innerHTML|\.outerHTML|\.insertAdjacentHTML|document\.write|document\.writeln)\s*=\s*.*(location\.|document\.(URL|referrer)|window\.name)",
        "description": "Ghi trực tiếp dữ liệu từ URL/referrer vào DOM.",
        "recommendation": "Dùng .textContent hoặc .innerText thay vì .innerHTML.",
    },
    {
        "id": "SEC076",
        "name": "React DangerouslySetInnerHTML",
        "severity": "high",
        "category": "xss",
        "pattern": r"dangerouslySetInnerHTML\s*=\s*\{\s*\{\s*__html\s*:\s*[^}]+\}\s*\}",
        "description": "Sử dụng dangerouslySetInnerHTML có nguy cơ cao bị XSS.",
        "recommendation": "Đảm bảo dữ liệu đã được sanitize (vd: DOMPurify) trước khi set.",
    },

    # ── CWE-22: PATH TRAVERSAL ─────────────────────────────────────────────
    {
        "id": "SEC077",
        "name": "Path Traversal (PHP)",
        "severity": "high",
        "category": "path_traversal",
        "pattern": r"(?i)(file_get_contents|fopen|readfile|unlink)\s*\(\s*.*\$_(GET|POST|REQUEST|COOKIE)",
        "description": "Đọc hoặc thao tác file bằng đường dẫn do người dùng kiểm soát.",
        "recommendation": "Dùng realpath() và basename() để kiểm tra đường dẫn.",
    },
    {
        "id": "SEC078",
        "name": "Path Traversal (Java)",
        "severity": "high",
        "category": "path_traversal",
        "pattern": r"(?i)new\s+File\s*\(\s*.*request\.getParameter",
        "description": "Tạo File object từ dữ liệu người dùng không kiểm soát.",
        "recommendation": "Sử dụng cơ chế whitelist hoặc validate kỹ input đường dẫn.",
    },

    # ── CWE-611: XML EXTERNAL ENTITY (XXE) ─────────────────────────────────
    {
        "id": "SEC079",
        "name": "XXE (Java SAXParser/DocumentBuilder)",
        "severity": "critical",
        "category": "xxe",
        "pattern": r"(?i)(SAXParserFactory|DocumentBuilderFactory)\.newInstance\(\)(?!\.setFeature)",
        "description": "Trình phân tích XML không vô hiệu hóa External Entities (XXE).",
        "recommendation": "Gọi factory.setFeature('http://apache.org/xml/features/disallow-doctype-decl', true).",
    },
    {
        "id": "SEC080",
        "name": "XXE (PHP libxml)",
        "severity": "critical",
        "category": "xxe",
        "pattern": r"(?i)(simplexml_load_string|DOMDocument::loadXML)\s*\(",
        "description": "Hàm XML mặc định của PHP có thể bị XXE nếu version cũ hoặc không cấu hình tốt.",
        "recommendation": "Sử dụng libxml_disable_entity_loader(true) trước khi parse.",
    },
    {
        "id": "SEC081",
        "name": "XXE (Python lxml/xml)",
        "severity": "critical",
        "category": "xxe",
        "pattern": r"(?i)\b(lxml\.etree\.parse|xml\.etree\.ElementTree\.parse)\s*\(",
        "description": "Thư viện parse XML cơ bản dễ bị tấn công XXE.",
        "recommendation": "Sử dụng thư viện defusedxml thay thế (defusedxml.ElementTree).",
    },

    # ── CWE-94: CODE INJECTION ─────────────────────────────────────────────
    {
        "id": "SEC082",
        "name": "Code Injection (PHP assert / preg_replace e)",
        "severity": "critical",
        "category": "injection",
        "pattern": r"(?i)(assert\s*\(\s*\$|preg_replace\s*\(\s*['\"].*?e.*?['\"])",
        "description": "Thực thi code tùy ý qua assert() hoặc preg_replace() với modifier /e.",
        "recommendation": "Tuyệt đối không dùng assert() để kiểm tra logic kinh doanh, loại bỏ /e trong Regex.",
    },
    {
        "id": "SEC083",
        "name": "Code Injection (JS Function Constructor)",
        "severity": "critical",
        "category": "dangerous_function",
        "pattern": r"\bnew\s+Function\s*\(",
        "description": "Hàm khởi tạo Function() đánh giá chuỗi dưới dạng code JS, tương tự eval().",
        "recommendation": "Tránh dùng new Function() với dữ liệu động.",
    },

    # ── CWE-502: DESERIALIZATION OF UNTRUSTED DATA ─────────────────────────
    {
        "id": "SEC084",
        "name": "Insecure Deserialization (PHP)",
        "severity": "critical",
        "category": "deserialization",
        "pattern": r"\bunserialize\s*\(\s*(?:\$_(GET|POST|REQUEST|COOKIE)|php://input)",
        "description": "unserialize() dữ liệu từ người dùng dẫn đến Object Injection / RCE.",
        "recommendation": "Sử dụng json_decode() thay thế cho serialize/unserialize.",
    },
    {
        "id": "SEC085",
        "name": "Insecure Deserialization (Node.js node-serialize)",
        "severity": "critical",
        "category": "deserialization",
        "pattern": r"(?i)\.unserialize\s*\(",
        "description": "Thư viện node-serialize hoặc tương tự cho phép RCE khi unserialize.",
        "recommendation": "Sử dụng JSON.parse().",
    },

    # ── CWE-327: BROKEN OR RISKY CRYPTO ALGORITHM ──────────────────────────
    {
        "id": "SEC086",
        "name": "Weak Hash / Crypto (Java)",
        "severity": "high",
        "category": "weak_crypto",
        "pattern": r"(?i)MessageDigest\.getInstance\s*\(\s*['\"](MD5|SHA-1|DES|RC4)['\"]\s*\)",
        "description": "Sử dụng thuật toán mã hóa / băm đã bị phá vỡ (MD5, SHA-1, DES, RC4).",
        "recommendation": "Chuyển sang SHA-256 (hoặc cao hơn) hoặc AES.",
    },

    # ── CWE-798: HARDCODED CREDENTIALS (EXTENDED) ──────────────────────────
    {
        "id": "SEC087",
        "name": "Basic Auth Hardcoded",
        "severity": "high",
        "category": "hardcoded_secret",
        "pattern": r"(?i)(Authorization:\s*Basic\s+[A-Za-z0-9+/=]{10,})",
        "description": "Chuỗi Basic Auth (chứa username:password) bị hardcode.",
        "recommendation": "Đọc chuỗi Basic Auth từ biến môi trường.",
    },

    # ── CWE-295: IMPROPER CERTIFICATE VALIDATION ───────────────────────────
    {
        "id": "SEC088",
        "name": "Bypass SSL/TLS Validation (Java)",
        "severity": "critical",
        "category": "insecure_network",
        "pattern": r"(?i)(X509TrustManager|HostnameVerifier)\s*\{\s*public\s+(?:void|boolean)\s+(?:check(?:Client|Server)Trusted|verify)\s*\(.*?\)\s*\{\s*(?:return\s+true;)?\s*\}",
        "description": "Tạo TrustManager hoặc HostnameVerifier trống để bypass lỗi SSL.",
        "recommendation": "Cấu hình TrustStore chuẩn, không bao giờ tin tưởng mù quáng mọi Certificate.",
    },
    {
        "id": "SEC089",
        "name": "Node.js TLS Reject Unauthorized",
        "severity": "critical",
        "category": "insecure_network",
        "pattern": r"(?i)NODE_TLS_REJECT_UNAUTHORIZED\s*['\"]?\s*:\s*['\"]?0['\"]?",
        "description": "Tắt xác thực chứng chỉ TLS trên toàn bộ ứng dụng Node.js.",
        "recommendation": "Gỡ bỏ cấu hình này. Cấu hình đúng custom CA nếu cần.",
    },

    # ── CWE-352: CROSS-SITE REQUEST FORGERY (CSRF) ─────────────────────────
    {
        "id": "SEC090",
        "name": "CSRF Protection Disabled (Spring Security)",
        "severity": "high",
        "category": "misconfiguration",
        "pattern": r"(?i)\.csrf\s*\(\s*\)\s*\.\s*disable\s*\(\s*\)",
        "description": "Vô hiệu hóa cơ chế chống CSRF trong Spring Security.",
        "recommendation": "Bật CSRF bảo vệ, đặc biệt là với các endpoint sử dụng session/cookie authentication.",
    },

    # ── CWE-918: SERVER-SIDE REQUEST FORGERY (SSRF) ────────────────────────
    {
        "id": "SEC091",
        "name": "SSRF (Python requests/urllib)",
        "severity": "critical",
        "category": "ssrf",
        "pattern": r"(?i)(requests\.(get|post|put|delete)|urllib\.request\.urlopen)\s*\(\s*.*(request\.|request_data|params|args|kwargs|url)",
        "description": "Thực hiện HTTP Request tới URL do người dùng cung cấp (SSRF).",
        "recommendation": "Kiểm tra URL có nằm trong whitelist không trước khi gọi, chặn dải IP nội bộ.",
    },
    {
        "id": "SEC092",
        "name": "SSRF (Node.js axios/fetch/request)",
        "severity": "critical",
        "category": "ssrf",
        "pattern": r"(?i)(axios|fetch|request\.get)\s*\(\s*.*req\.(body|query|params)\.",
        "description": "Gọi HTTP request tới URL lấy từ input của request (Node.js).",
        "recommendation": "Cần filter và whitelist URL kỹ càng.",
    },
    {
        "id": "SEC093",
        "name": "SSRF (PHP curl/file_get_contents)",
        "severity": "critical",
        "category": "ssrf",
        "pattern": r"(?i)(curl_setopt.*CURLOPT_URL|file_get_contents)\s*\(.*\$_(GET|POST|REQUEST)",
        "description": "Chỉ định URL curl hoặc file_get_contents bằng dữ liệu ngoài (PHP).",
        "recommendation": "Phải xác thực URL qua filter_var với FILTER_VALIDATE_URL.",
    },

    # ── CWE-601: OPEN REDIRECT ─────────────────────────────────────────────
    {
        "id": "SEC094",
        "name": "Open Redirect (Express/Node.js)",
        "severity": "high",
        "category": "open_redirect",
        "pattern": r"(?i)res\.redirect\s*\(\s*req\.(query|body)\.",
        "description": "Chuyển hướng người dùng dựa vào tham số đầu vào không được kiểm chứng.",
        "recommendation": "Chỉ redirect tới các đường dẫn tương đối hoặc các URL đã được whitelist.",
    },
    {
        "id": "SEC095",
        "name": "Open Redirect (Python/Django/Flask)",
        "severity": "high",
        "category": "open_redirect",
        "pattern": r"(?i)(redirect|HttpResponseRedirect)\s*\(\s*request\.(GET|POST|args|form)",
        "description": "Chuyển hướng HTTP dựa vào dữ liệu request (Python).",
        "recommendation": "Sử dụng url_has_allowed_host_and_scheme() (Django) hoặc kiểm tra tương tự.",
    },
    {
        "id": "SEC096",
        "name": "Open Redirect (PHP header)",
        "severity": "high",
        "category": "open_redirect",
        "pattern": r"(?i)header\s*\(\s*['\"]Location:\s*['\"]\s*\.\s*\$_(GET|POST|REQUEST)",
        "description": "Redirect người dùng qua hàm header() bằng dữ liệu ngoài.",
        "recommendation": "Cố định hostname hoặc dùng whitelist.",
    },

    # ── CWE-942: OVERLY PERMISSIVE CORS POLICY ─────────────────────────────
    {
        "id": "SEC097",
        "name": "CORS Allow-Origin Wildcard",
        "severity": "high",
        "category": "misconfiguration",
        "pattern": r"(?i)Access-Control-Allow-Origin\s*['\"]?\s*:\s*['\"]?\*['\"]?",
        "description": "CORS Policy cho phép mọi domain (*).",
        "recommendation": "Chỉ allow origin cụ thể cần thiết.",
    },
    {
        "id": "SEC098",
        "name": "CORS Dynamic Origin Reflection",
        "severity": "critical",
        "category": "misconfiguration",
        "pattern": r"(?i)Access-Control-Allow-Origin.*?req\.headers\.origin",
        "description": "Phản xạ trực tiếp header Origin của người dùng làm Allow-Origin.",
        "recommendation": "Kiểm tra Origin có thuộc danh sách an toàn không rồi mới phản xạ.",
    },

    # ── CWE-614 / CWE-1004: INSECURE COOKIE FLAGS ──────────────────────────
    {
        "id": "SEC099",
        "name": "Insecure Cookie (secure: false)",
        "severity": "medium",
        "category": "misconfiguration",
        "pattern": r"(?i)(res\.cookie.*secure\s*:\s*false|setcookie.*false)",
        "description": "Cookie chứa session nhưng không có cờ Secure.",
        "recommendation": "Cài đặt cờ Secure=true để cookie chỉ truyền qua HTTPS.",
    },
    {
        "id": "SEC100",
        "name": "Insecure Cookie (httpOnly: false)",
        "severity": "medium",
        "category": "misconfiguration",
        "pattern": r"(?i)(res\.cookie.*httpOnly\s*:\s*false|setcookie.*false)",
        "description": "Cookie có thể bị truy cập bởi JavaScript (thiếu HttpOnly).",
        "recommendation": "Cài đặt cờ HttpOnly=true cho session cookie.",
    },

    # ── CWE-338: CRYPTOGRAPHICALLY WEAK PRNG ───────────────────────────────
    {
        "id": "SEC101",
        "name": "Weak PRNG (Math.random)",
        "severity": "medium",
        "category": "weak_crypto",
        "pattern": r"\bMath\.random\s*\(",
        "description": "Sử dụng Math.random() cho các tác vụ tạo token/password/crypto.",
        "recommendation": "Sử dụng crypto.randomBytes() hoặc window.crypto.getRandomValues().",
    },
    {
        "id": "SEC102",
        "name": "Weak PRNG (PHP rand/mt_rand)",
        "severity": "medium",
        "category": "weak_crypto",
        "pattern": r"\b(rand|mt_rand|uniqid)\s*\(",
        "description": "Các hàm random cơ bản của PHP không an toàn cho bảo mật.",
        "recommendation": "Sử dụng random_int() hoặc random_bytes().",
    },

    # ── CWE-319: CLEARTEXT TRANSMISSION OF SENSITIVE INFO ──────────────────
    {
        "id": "SEC103",
        "name": "Cleartext Protocols (FTP/Telnet/HTTP)",
        "severity": "high",
        "category": "insecure_network",
        "pattern": r"(?i)['\"](ftp|telnet|http)://[a-zA-Z0-9.\-]+['\"]",
        "description": "Sử dụng giao thức không mã hóa (FTP, Telnet, HTTP) để truyền dữ liệu.",
        "recommendation": "Chuyển sang SFTP, SSH, HTTPS.",
        "whitelist_pattern": r"(?i)['\"]http://(localhost|127\.0\.0\.1|0\.0\.0\.0|[^']*\.xml|[^']*\.dtd)['\"]",
    },

    # ── CWE-312: CLEARTEXT STORAGE OF SENSITIVE INFO ───────────────────────
    {
        "id": "SEC104",
        "name": "Sensitive Info in LocalStorage",
        "severity": "high",
        "category": "sensitive_storage",
        "pattern": r"(?i)localStorage\.setItem\s*\(\s*['\"](password|token|secret|key|jwt)['\"]",
        "description": "Lưu trữ thông tin nhạy cảm vào localStorage.",
        "recommendation": "Sử dụng HttpOnly Cookies để lưu token, không lưu trong LocalStorage vì dễ bị XSS đánh cắp.",
    },

    # ── CWE-119 / CWE-120: BUFFER COPY WITHOUT CHECKING SIZE ───────────────
    {
        "id": "SEC105",
        "name": "C/C++ scanf without width",
        "severity": "critical",
        "category": "buffer_overflow",
        "pattern": r"(?i)\b(scanf|fscanf|sscanf)\s*\(\s*['\"][^'\"]*%s",
        "description": "Sử dụng %s trong scanf không giới hạn chiều dài gây Buffer Overflow.",
        "recommendation": "Sử dụng format string giới hạn độ dài (ví dụ: %255s).",
    },
    {
        "id": "SEC106",
        "name": "C/C++ memcpy/memset overlapping",
        "severity": "high",
        "category": "buffer_overflow",
        "pattern": r"\b(memcpy|memset)\s*\([^,]+,[^,]+,\s*(strlen\([^)]+\)|[a-zA-Z_0-9]+)\)",
        "description": "Cẩn trọng khi dùng memcpy/memset với tham số size động có nguy cơ tràn bộ đệm.",
        "recommendation": "Đảm bảo size không vượt quá kích thước cấp phát của dest buffer.",
    },

    # ── CWE-1333: INEFFICIENT REGULAR EXPRESSION (ReDoS) ───────────────────
    {
        "id": "SEC107",
        "name": "Regex Denial of Service (ReDoS)",
        "severity": "high",
        "category": "dos",
        "pattern": r"([a-zA-Z0-9.\-_\\s]\+)\+\/?",
        "description": "Cú pháp Regex lặp lồng nhau có thể gây Regex Denial of Service.",
        "recommendation": "Hạn chế sử dụng (+)+ hoặc (*)* trong Regex, dùng các thư viện an toàn.",
    },

    # ── CWE-754: IMPROPER CHECK FOR UNUSUAL CONDITIONS ─────────────────────
    {
        "id": "SEC108",
        "name": "Missing Error Handling (Empty Catch)",
        "severity": "low",
        "category": "misconfiguration",
        "pattern": r"catch\s*\([^\)]*\)\s*\{\s*\}",
        "description": "Khối try-catch bắt lỗi nhưng để trống (Empty Catch Block).",
        "recommendation": "Nên log lỗi hoặc xử lý một cách cụ thể thay vì swallow Exception.",
    },

    # ── CWE-326: INADEQUATE ENCRYPTION STRENGTH ────────────────────────────
    {
        "id": "SEC109",
        "name": "Weak RSA Key Size (< 2048)",
        "severity": "high",
        "category": "weak_crypto",
        "pattern": r"(?i)KeyPairGenerator\.getInstance\s*\(\s*['\"]RSA['\"]\s*\).*?\.initialize\s*\(\s*(512|1024)\s*\)",
        "description": "Tạo cặp khóa RSA với độ dài yếu (512 hoặc 1024 bit).",
        "recommendation": "Sử dụng độ dài khóa tối thiểu 2048 bit.",
    },

    # ── CWE-190: INTEGER OVERFLOW/WRAPAROUND ───────────────────────────────
    {
        "id": "SEC110",
        "name": "C/C++ Integer Overflow Functions",
        "severity": "medium",
        "category": "integer_overflow",
        "pattern": r"\b(atoi|atol|atoll)\s*\(",
        "description": "Sử dụng atoi/atol không an toàn khi tràn số, kết quả không xác định.",
        "recommendation": "Sử dụng strtol, strtoll và kiểm tra errno (ERANGE).",
    },
    {
        "id": "SEC004",
        "name": "Hardcoded password",
        "severity": "critical",
        "category": "hardcoded_secret",
        "pattern": r"(?i)(password|passwd|pwd|db_pass|db_password)\s*=\s*['\"][^'\"]{4,}['\"]",
        "description": "Mật khẩu được hardcode dưới dạng string literal.",
        "recommendation": "Dùng environment variable hoặc secret manager. Không commit .env.",
        "whitelist_pattern": r"(?i)(password|passwd|pwd)\s*=\s*['\"](\"|'|\s*|<.+>|\{.+\}|\$\{.+\}|your.password|changeme|placeholder|todo|example|test|fake|mock|dummy)['\"]",
    },
    {
        "id": "SEC005",
        "name": "Private key / certificate",
        "severity": "critical",
        "category": "hardcoded_secret",
        "pattern": r"-----BEGIN (RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----",
        "description": "Private key được nhúng trực tiếp vào code.",
        "recommendation": "Lưu key trong file riêng, thêm vào .gitignore, dùng secrets manager.",
    },
    {
        "id": "SEC006",
        "name": "GitHub / GitLab token",
        "severity": "critical",
        "category": "hardcoded_secret",
        "pattern": r"(ghp_[A-Za-z0-9]{36}|glpat-[A-Za-z0-9\-]{20})",
        "description": "Personal access token của GitHub hoặc GitLab.",
        "recommendation": "Thu hồi token ngay. Dùng environment variable.",
    },
    {
        "id": "SEC007",
        "name": "Slack / Stripe / Twilio token",
        "severity": "critical",
        "category": "hardcoded_secret",
        "pattern": r"(xox[baprs]-[A-Za-z0-9\-]{10,}|sk_live_[A-Za-z0-9]{24,}|AC[a-z0-9]{32}|SK[a-z0-9]{32})",
        "description": "Token của Slack, Stripe (live), hoặc Twilio.",
        "recommendation": "Thu hồi và rotate ngay. Dùng environment variable.",
    },
    {
    "id": "SEC008",
    "name": "OpenAI API Key",
    "severity": "critical",
    "category": "hardcoded_secret",
    "pattern": r"sk-(?:proj-)?[A-Za-z0-9_\-]{20,}",
    "description": "OpenAI API key có thể bị hardcode trong source/config.",
    "recommendation": "Thu hồi key nếu đã commit. Đọc từ environment variable hoặc secret manager.",
},
{
    "id": "SEC009",
    "name": "Anthropic API Key",
    "severity": "critical",
    "category": "hardcoded_secret",
    "pattern": r"sk-ant-[A-Za-z0-9_\-]{20,}",
    "description": "Anthropic API key có thể bị hardcode.",
    "recommendation": "Rotate key và chuyển sang secret manager.",
},
{
    "id": "SEC010",
    "name": "Google API Key",
    "severity": "critical",
    "category": "hardcoded_secret",
    "pattern": r"AIza[0-9A-Za-z_\-]{35}",
    "description": "Google API key bị hardcode.",
    "recommendation": "Restrict key theo domain/IP/API scope và chuyển sang biến môi trường.",
},
{
    "id": "SEC011",
    "name": "HuggingFace Token",
    "severity": "critical",
    "category": "hardcoded_secret",
    "pattern": r"hf_[A-Za-z0-9]{20,}",
    "description": "HuggingFace token bị hardcode.",
    "recommendation": "Revoke token và đọc từ environment variable.",
},
{
    "id": "SEC012",
    "name": "JWT Token",
    "severity": "high",
    "category": "hardcoded_secret",
    "pattern": r"eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}",
    "description": "JWT token xuất hiện trực tiếp trong source/config.",
    "recommendation": "Không hardcode JWT. Dùng session/token runtime và không commit token thật.",
},
{
    "id": "SEC013",
    "name": "Database URL with credentials",
    "severity": "critical",
    "category": "hardcoded_secret",
    "pattern": r"(?i)(postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis)://[^:\s'\"]+:[^@\s'\"]+@[^'\"]+",
    "description": "Database connection string chứa username/password.",
    "recommendation": "Đưa database URL vào secret manager hoặc environment variable. Rotate password nếu đã leak.",
},
{
    "id": "SEC014",
    "name": "Bearer Token in Header",
    "severity": "critical",
    "category": "hardcoded_secret",
    "pattern": r"(?i)(authorization|auth_header|headers)\s*[:=]\s*.*Bearer\s+[A-Za-z0-9._\-]{20,}",
    "description": "Authorization Bearer token bị hardcode trong header.",
    "recommendation": "Không commit Bearer token. Inject token từ environment/runtime.",
},
{
    "id": "SEC015",
    "name": "NPM Token",
    "severity": "critical",
    "category": "hardcoded_secret",
    "pattern": r"(npm_[A-Za-z0-9]{20,}|//registry\.npmjs\.org/:_authToken\s*=\s*[A-Za-z0-9_\-]{20,})",
    "description": "NPM auth token bị hardcode hoặc commit trong config.",
    "recommendation": "Revoke token trong npm account và dùng CI/CD secret.",
},
{
    "id": "SEC016",
    "name": "PyPI Token",
    "severity": "critical",
    "category": "hardcoded_secret",
    "pattern": r"pypi-[A-Za-z0-9_\-]{20,}",
    "description": "PyPI token bị hardcode.",
    "recommendation": "Revoke token và dùng secret trong CI/CD.",
},
{
    "id": "SEC017",
    "name": "Telegram Bot Token",
    "severity": "critical",
    "category": "hardcoded_secret",
    "pattern": r"\b\d{8,10}:[A-Za-z0-9_\-]{30,}\b",
    "description": "Telegram bot token có thể bị hardcode.",
    "recommendation": "Revoke token qua BotFather và đọc token từ environment variable.",
},
{
    "id": "SEC018",
    "name": "Discord Webhook URL",
    "severity": "critical",
    "category": "hardcoded_secret",
    "pattern": r"https://discord(?:app)?\.com/api/webhooks/[0-9]+/[A-Za-z0-9_\-]+",
    "description": "Discord webhook URL bị hardcode.",
    "recommendation": "Xóa webhook cũ, tạo webhook mới và lưu trong secret manager.",
},
{
    "id": "SEC019",
    "name": "Supabase URL or Key",
    "severity": "high",
    "category": "hardcoded_secret",
    "pattern": r"(?i)(supabase.{0,30}(anon|service_role|key)|service_role_key)\s*[:=]\s*['\"][A-Za-z0-9._\-]{20,}['\"]",
    "description": "Supabase anon/service role key có thể bị hardcode.",
    "recommendation": "Không expose service_role key ở frontend. Dùng backend secret/env.",
},
{
    "id": "SEC020",
    "name": "Generic secret in env/config",
    "severity": "high",
    "category": "hardcoded_secret",
    "pattern": r"(?i)\b[A-Z0-9_]*(SECRET|TOKEN|API_KEY|PRIVATE_KEY|ACCESS_KEY|CLIENT_SECRET)[A-Z0-9_]*\s*[:=]\s*['\"]?[A-Za-z0-9_\-./+=]{16,}['\"]?",
    "description": "Biến secret/token/api key xuất hiện trong file env/config/source.",
    "recommendation": "Kiểm tra đây có phải secret thật không. Nếu thật, rotate và chuyển sang secret manager.",
    "whitelist_pattern": r"(?i)(example|dummy|fake|mock|placeholder|changeme|your_|xxx|<.+>|\$\{.+\})",
},

    # ── DANGEROUS FUNCTIONS ────────────────────────────────────────────────
    {
        "id": "SEC021",
        "name": "eval() call",
        "severity": "critical",
        "category": "dangerous_function",
        "pattern": r"\beval\s*\(",
        "description": "eval() thực thi code tùy ý — RCE nếu input từ user.",
        "recommendation": "Xóa eval(). Nếu cần parse, dùng ast.literal_eval() cho dữ liệu đơn giản.",
    },
    {
        "id": "SEC022",
        "name": "exec() call",
        "severity": "critical",
        "category": "dangerous_function",
        "pattern": r"\bexec\s*\(",
        "description": "exec() thực thi code Python tùy ý — RCE nếu input không được kiểm soát.",
        "recommendation": "Tránh exec(). Refactor thành function call thông thường.",
    },
    {
        "id": "SEC023",
        "name": "pickle.loads / pickle.load",
        "severity": "critical",
        "category": "dangerous_function",
        "pattern": r"\bpickle\.(loads?|Unpickler)\s*\(",
        "description": "pickle.loads() có thể execute code tùy ý khi deserialize — RCE.",
        "recommendation": "Dùng json.loads() + pydantic/marshmallow để validate. Không deserialize dữ liệu untrusted.",
    },
    {
        "id": "SEC024",
        "name": "os.system() call",
        "severity": "critical",
        "category": "dangerous_function",
        "pattern": r"\bos\.system\s*\(",
        "description": "os.system() dễ bị shell injection nếu có string concatenation.",
        "recommendation": "Dùng subprocess.run(['cmd', 'arg'], check=True) — truyền list, không phải string.",
    },
    {
        "id": "SEC025",
        "name": "subprocess shell=True",
        "severity": "high",
        "category": "dangerous_function",
        "pattern": r"\bsubprocess\.(run|call|Popen|check_output|check_call)\s*\([^)]*shell\s*=\s*True",
        "description": "shell=True với subprocess kích hoạt shell interpolation — injection risk.",
        "recommendation": "Dùng shell=False (mặc định) và truyền argument dưới dạng list.",
    },
    {
        "id": "SEC026",
        "name": "compile() with dynamic code",
        "severity": "high",
        "category": "dangerous_function",
        "pattern": r"\bcompile\s*\(.{0,80}exec",
        "description": "compile() kết hợp với exec có thể chạy code tùy ý.",
        "recommendation": "Tránh pattern này. Dùng function/class thông thường.",
    },
    {
        "id": "SEC027",
        "name": "__import__() dynamic import",
        "severity": "high",
        "category": "dangerous_function",
        "pattern": r"\b__import__\s*\(",
        "description": "__import__() với input từ user cho phép load module tùy ý.",
        "recommendation": "Dùng importlib với whitelist module được phép.",
    },
    {
        "id": "SEC028",
        "name": "yaml.load() without Loader",
        "severity": "high",
        "category": "dangerous_function",
        "pattern": r"\byaml\.load\s*\([^)]*\)",
        "description": "yaml.load() không có Loader=yaml.SafeLoader có thể execute code.",
        "recommendation": "Dùng yaml.safe_load() hoặc yaml.load(data, Loader=yaml.SafeLoader).",
        "whitelist_pattern": r"yaml\.load\s*\([^)]*SafeLoader|yaml\.load\s*\([^)]*BaseLoader",
    },

    # ── WEAK CRYPTOGRAPHY ──────────────────────────────────────────────────
    {
        "id": "SEC029",
        "name": "MD5 hash",
        "severity": "high",
        "category": "weak_crypto",
        "pattern": r"\bhashlib\.md5\s*\(",
        "description": "MD5 bị broken — không dùng để hash mật khẩu hoặc dữ liệu nhạy cảm.",
        "recommendation": "Dùng argon2-cffi hoặc bcrypt cho password. SHA-256 cho checksum file.",
    },
    {
        "id": "SEC030",
        "name": "SHA1 hash",
        "severity": "high",
        "category": "weak_crypto",
        "pattern": r"\bhashlib\.sha1\s*\(",
        "description": "SHA1 đã bị tấn công collision — không dùng cho mục đích bảo mật.",
        "recommendation": "Dùng hashlib.sha256() hoặc cao hơn. Với password: argon2/bcrypt.",
    },
    {
        "id": "SEC031",
        "name": "DES encryption",
        "severity": "high",
        "category": "weak_crypto",
        "pattern": r"(?i)\b(DES|3DES|TripleDES)\b",
        "description": "DES/3DES có key quá ngắn, đã lỗi thời.",
        "recommendation": "Dùng AES-256-GCM (cryptography library).",
    },
    {
        "id": "SEC032",
        "name": "Hardcoded IV / nonce",
        "severity": "high",
        "category": "weak_crypto",
        "pattern": r"(?i)(iv|nonce)\s*=\s*b?['\"][^'\"]{8,}['\"]",
        "description": "IV hoặc nonce cố định phá vỡ semantic security của cipher.",
        "recommendation": "Luôn generate IV ngẫu nhiên: iv = os.urandom(16)",
    },
    {
        "id": "SEC033",
        "name": "random instead of secrets",
        "severity": "medium",
        "category": "weak_crypto",
        "pattern": r"\brandom\.(random|randint|choice|randrange|shuffle)\s*\(",
        "description": "random module không cryptographically secure — không dùng cho token/OTP.",
        "recommendation": "Dùng secrets module: secrets.token_hex(), secrets.choice().",
    },

    # ── SENSITIVE DATA IN LOGS ─────────────────────────────────────────────
    {
        "id": "SEC034",
        "name": "Password in log",
        "severity": "high",
        "category": "sensitive_log",
        "pattern": r"(?i)(log(ger)?|print)\s*.*\b(password|passwd|pwd|secret|token|api_key)\b",
        "description": "Dữ liệu nhạy cảm có thể bị ghi vào log.",
        "recommendation": "Mask dữ liệu: logger.info(f'User {user_id}') — không log password/token.",
    },
    {
        "id": "SEC035",
        "name": "Credit card pattern in log",
        "severity": "high",
        "category": "sensitive_log",
        "pattern": r"(?i)(log(ger)?|print)\s*.*\b(card|credit|cvv|pan)\b",
        "description": "Thông tin thẻ tín dụng có thể bị ghi vào log.",
        "recommendation": "Không bao giờ log PCI data. Mask hoặc tokenize trước.",
    },

    # ── PATH TRAVERSAL ─────────────────────────────────────────────────────
    {
        "id": "SEC036",
        "name": "open() with user-controlled path",
        "severity": "high",
        "category": "path_traversal",
        "pattern": r"\bopen\s*\(\s*(?![\'\"])[^)]{0,60}(request|param|arg|input|user|filename|path)[^)]{0,60}\)",
        "description": "open() có thể nhận path từ user input — path traversal risk (../../etc/passwd).",
        "recommendation": "Dùng Path.resolve() và kiểm tra prefix: assert str(target).startswith(str(BASE_DIR))",
    },

    # ── INSECURE NETWORK ───────────────────────────────────────────────────
    {
        "id": "SEC037",
        "name": "SSL verify=False",
        "severity": "high",
        "category": "insecure_network",
        "pattern": r"\bverify\s*=\s*False",
        "description": "Tắt SSL verification — dễ bị MITM attack.",
        "recommendation": "Luôn dùng verify=True (mặc định). Nếu cần cert tự ký, truyền path cert.",
    },
    {
        "id": "SEC038",
        "name": "HTTP (not HTTPS) hardcoded URL",
        "severity": "medium",
        "category": "insecure_network",
        "pattern": r"['\"]http://(?!localhost|127\.0\.0\.1|0\.0\.0\.0)[^'\"]{5,}['\"]",
        "description": "URL HTTP không mã hóa — dễ bị sniff/MITM trên production.",
        "recommendation": "Dùng HTTPS cho tất cả external endpoint.",
    },

    # ── SQL INJECTION HINTS ────────────────────────────────────────────────
    {
        "id": "SEC039",
        "name": "String formatting in SQL",
        "severity": "critical",
        "category": "injection",
        "pattern": r"(?i)(execute|executemany|raw|query)\s*\(\s*['\"]?\s*(SELECT|INSERT|UPDATE|DELETE|DROP|CREATE).{0,200}(%s|%d|{|}|format\s*\(|f['\"])",
        "description": "SQL query dùng string formatting thay vì parameterized — SQL injection risk.",
        "recommendation": "Dùng parameterized query: cursor.execute('SELECT * WHERE id=%s', (id,))",
    },
    {
        "id": "SEC040",
        "name": "f-string in SQL execute",
        "severity": "critical",
        "category": "injection",
        "pattern": r"(?i)(execute|raw|query)\s*\(\s*f['\"]",
        "description": "f-string trực tiếp trong execute() — SQL injection gần như chắc chắn.",
        "recommendation": "Tách query string và parameters: cursor.execute(query, params)",
    },

    # ── DEBUG / DEVELOPMENT FLAGS ──────────────────────────────────────────
    {
        "id": "SEC041",
        "name": "Debug mode enabled",
        "severity": "medium",
        "category": "misconfiguration",
        "pattern": r"(?i)(DEBUG\s*=\s*True|app\.run\s*\([^)]*debug\s*=\s*True)",
        "description": "Debug mode bật trong code — có thể leak stack trace và internal info.",
        "recommendation": "Đọc từ env: DEBUG = os.environ.get('DEBUG', 'False') == 'True'",
    },
    {
        "id": "SEC042",
        "name": "assert for security check",
        "severity": "medium",
        "category": "misconfiguration",
        "pattern": r"\bassert\b.{0,60}(auth|permission|role|admin|is_valid|logged_in)",
        "description": "assert bị vô hiệu khi chạy với python -O — không dùng cho security check.",
        "recommendation": "Dùng if/raise thay vì assert cho các kiểm tra bảo mật.",
    },
]


SCAN_EXTENSIONS = {
    ".env", ".yaml", ".yml", ".json", ".ini", ".conf", ".cfg", ".toml",
    ".py", ".pyw", ".sh", ".bash", ".zsh",
    ".js", ".jsx", ".ts", ".tsx", ".php", ".java", ".c", ".cpp", ".h", ".hpp", ".cs", ".go", ".rb", ".kt", ".swift", ".rs"
}

SCAN_FILENAMES = {
    ".env",
    ".env.local",
    ".env.development",
    ".env.production",
    ".env.staging",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    "package.json",
    "requirements.txt",
    "settings.py",
    "config.py",
}

SKIP_DIRS = {
    ".git", ".hg", ".svn",
    "node_modules", "__pycache__", ".pytest_cache",
    "venv", ".venv", "env",
    "dist", "build",
    ".mypy_cache", ".tox",
    ".next", "coverage",
}

SKIP_PATH_PARTS = {
    "migrations",
    "alembic",
}
